version: '3'
services:
  terraclassifier_app:
    container_name: terraclassifier_app
    build: ./terraclassifier_app            # Pfad zum Dockerfile der Webanwendung. Baut daraus ein Image 
    # image: astru/terraclassifier_app:latest
    ports:
      - "3000:3000"

  # openeocubes_custom:
  #  container_name: openeocubes_custom
  #  image: astru/openeocubes_custom:1.0
  #  environment:
  #    - AWSHOST=
  #    - TZ=Etc/UTC
  #    - DEBIAN_FRONTEND=noninteractive
  #  ports:
  #    - "8080:8080"
  #  restart: always