version: '3'
services:
  terraclassifier_app:
    container_name: terraclassifier_app
    build: ./terraclassifier_app
    ports:
      - "3000:3000"  
  
  terraclassifier_backend:
    container_name: terraclassifier_backend
    build: ./terraclassifier_backend
    ports:
      - "8080:8080"
    depends_on:
      - terraclassifier_app

  terraclassifier_r_backend:
    container_name: terraclassifier_r_backend
    build: ./terraclassifier_r_backend
    ports:
      - "8000:8000"              